meta_product_name: "Bizzy Bee"
meta_title: "Bizzy Bee | Get paid to bee you!"
meta_description: "Looking to make money on the side? With Bizzy Bee you can sell your unique skills with ease!"
meta_image: "cover.png"                       # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
